//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthNDecryptService.DocumentValidatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.project.com/", ConfigurationName="DocumentValidatorService.DocumentVerificationEndpoint")]
    public interface DocumentVerificationEndpoint {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément content de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.project.com/DocumentVerificationEndpoint/documentVerificationOperat" +
            "ionRequest", ReplyAction="http://facade.project.com/DocumentVerificationEndpoint/documentVerificationOperat" +
            "ionResponse")]
        AuthNDecryptService.DocumentValidatorService.documentVerificationOperationResponse documentVerificationOperation(AuthNDecryptService.DocumentValidatorService.documentVerificationOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.project.com/DocumentVerificationEndpoint/documentVerificationOperat" +
            "ionRequest", ReplyAction="http://facade.project.com/DocumentVerificationEndpoint/documentVerificationOperat" +
            "ionResponse")]
        System.Threading.Tasks.Task<AuthNDecryptService.DocumentValidatorService.documentVerificationOperationResponse> documentVerificationOperationAsync(AuthNDecryptService.DocumentValidatorService.documentVerificationOperationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class documentVerificationOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="documentVerificationOperation", Namespace="http://facade.project.com/", Order=0)]
        public AuthNDecryptService.DocumentValidatorService.documentVerificationOperationRequestBody Body;
        
        public documentVerificationOperationRequest() {
        }
        
        public documentVerificationOperationRequest(AuthNDecryptService.DocumentValidatorService.documentVerificationOperationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class documentVerificationOperationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string file;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key;
        
        public documentVerificationOperationRequestBody() {
        }
        
        public documentVerificationOperationRequestBody(string content, string file, string key) {
            this.content = content;
            this.file = file;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class documentVerificationOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="documentVerificationOperationResponse", Namespace="http://facade.project.com/", Order=0)]
        public AuthNDecryptService.DocumentValidatorService.documentVerificationOperationResponseBody Body;
        
        public documentVerificationOperationResponse() {
        }
        
        public documentVerificationOperationResponse(AuthNDecryptService.DocumentValidatorService.documentVerificationOperationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class documentVerificationOperationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool acceptedDocument;
        
        public documentVerificationOperationResponseBody() {
        }
        
        public documentVerificationOperationResponseBody(bool acceptedDocument) {
            this.acceptedDocument = acceptedDocument;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentVerificationEndpointChannel : AuthNDecryptService.DocumentValidatorService.DocumentVerificationEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentVerificationEndpointClient : System.ServiceModel.ClientBase<AuthNDecryptService.DocumentValidatorService.DocumentVerificationEndpoint>, AuthNDecryptService.DocumentValidatorService.DocumentVerificationEndpoint {
        
        public DocumentVerificationEndpointClient() {
        }
        
        public DocumentVerificationEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentVerificationEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentVerificationEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentVerificationEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthNDecryptService.DocumentValidatorService.documentVerificationOperationResponse AuthNDecryptService.DocumentValidatorService.DocumentVerificationEndpoint.documentVerificationOperation(AuthNDecryptService.DocumentValidatorService.documentVerificationOperationRequest request) {
            return base.Channel.documentVerificationOperation(request);
        }
        
        public bool documentVerificationOperation(string content, string file, string key) {
            AuthNDecryptService.DocumentValidatorService.documentVerificationOperationRequest inValue = new AuthNDecryptService.DocumentValidatorService.documentVerificationOperationRequest();
            inValue.Body = new AuthNDecryptService.DocumentValidatorService.documentVerificationOperationRequestBody();
            inValue.Body.content = content;
            inValue.Body.file = file;
            inValue.Body.key = key;
            AuthNDecryptService.DocumentValidatorService.documentVerificationOperationResponse retVal = ((AuthNDecryptService.DocumentValidatorService.DocumentVerificationEndpoint)(this)).documentVerificationOperation(inValue);
            return retVal.Body.acceptedDocument;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthNDecryptService.DocumentValidatorService.documentVerificationOperationResponse> AuthNDecryptService.DocumentValidatorService.DocumentVerificationEndpoint.documentVerificationOperationAsync(AuthNDecryptService.DocumentValidatorService.documentVerificationOperationRequest request) {
            return base.Channel.documentVerificationOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthNDecryptService.DocumentValidatorService.documentVerificationOperationResponse> documentVerificationOperationAsync(string content, string file, string key) {
            AuthNDecryptService.DocumentValidatorService.documentVerificationOperationRequest inValue = new AuthNDecryptService.DocumentValidatorService.documentVerificationOperationRequest();
            inValue.Body = new AuthNDecryptService.DocumentValidatorService.documentVerificationOperationRequestBody();
            inValue.Body.content = content;
            inValue.Body.file = file;
            inValue.Body.key = key;
            return ((AuthNDecryptService.DocumentValidatorService.DocumentVerificationEndpoint)(this)).documentVerificationOperationAsync(inValue);
        }
    }
}
